### PR TITLE
fix: multichar tigger with allowWhitespace

### LINKED ISSUE #194: allowWhitespace breaks search trigger
demo

In the above, I have two triggers. One for `((` (which allows whitespace), one for `#` (which does not). You can see when I type the `((` trigger, additional input doesn't update the search, whereas using `#` it updates appropriately 

When whitespaces are allowed, the dataProvider doesn't seem to be making subsequent search calls after the initial letter is entered. 

Code in case it's relevant:
```
    '((': {
      allowWhitespace: true,
      dataProvider: async (token: string) => {
        const text = token.substr(1)
        const result = await searchBlocks(text)
        const parsed = result.map(({ text, id }) => {
          return { text, id }
        })
        return parsed
      },
      component: BlockItem,
      output: (item: any) => `((${item.id}))`,
    },
```

I can probably come up with a workaround, but still seems worth filling. Do I have something set up incorrectly?

Loving the package otherwise! Works great

### PR DESCRIPTION
**Pull request by jukben**
close #194 

Ah, it looks I accidentally reformatted the code 🤦

### CODE REVIEW

**Comment by jukben** [comment]
Hey! Thank you so much for your PR!

[Here is the playground for this revision](https://1530-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

_This message has been generated [automagically](https://github.com/jukben/rta-bot) ✨_

File: src/Textarea.jsx [hunk 1]
```diff
@@ -850,7 +855,11 @@ class ReactTextareaAutocomplete extends React.Component<
       }
 
       currentTrigger =
-        Object.keys(trigger).find(a => a === lastToken[0]) || null;
```
Comment (jukben) [inline src/Textarea.jsx:853]: Actual change
